logging:
  level:
    org.zalando.logbook: trace
    sql: debug
    root: warn
spring:
  banner:
    location: classpath:banners/banner-test.txt
  main:
    log-startup-info: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:file:./db/filmorate;
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect