logging:
  level:
    org.zalando.logbook: trace
    sql: debug
    ru.yandex.practicum.filmorate: debug
spring:
  banner:
    location: classpath:banners/banner-dev.txt
  main:
    log-startup-info: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never